name: Update Daily Words

on:
  schedule:
    - cron:  '0 0 * * *' #run every day at 00:00 (GMT+1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Run the script
      run: python ./scripts/create_daily_words.py
